# Generated by Django 5.1.4 on 2025-01-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('university_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField()),
                ('website_url', models.URLField()),
                ('accreditation_details', models.TextField()),
                ('total_institutes', models.PositiveIntegerField()),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('establishment_year', models.PositiveIntegerField()),
                ('chancellor_name', models.CharField(max_length=255)),
            ],
        ),
    ]
