# Generated by Django 5.1.4 on 2025-01-27 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='DEPT_NAME',
            field=models.CharField(choices=[('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('EE', 'Electrical Engineering'), ('CSE', 'Computer Science Engineering'), ('CHE', 'Chemical Engineering'), ('AE', 'Aerospace Engineering'), ('BME', 'Biomedical Engineering'), ('ENE', 'Environmental Engineering'), ('IE', 'Industrial Engineering'), ('MTE', 'Materials Engineering')], default='ME', max_length=50),
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.user')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.user')),
            ],
        ),
    ]
